### ISSUE TITLE
Gravity will combine payload's information.

### ISSUE THREAD

**Issue by TaroBill** [BrobridgeOrg/gravity-cli#10]
We observe that when we publish faster, the result of payload will combine information. 
We expect individual publish do not effect each other.

version:
gravity-cli : [47ca8b652eb4b3032934fb348d07b0f7c889d687]
dispatcher: [49572419a6250899476c68e01159f27fe741c7da]
nats image: nats:2.10.14-alpine3.19

## Reproduce:

1. Open nats and dispatcher
![image](https://github.com/BrobridgeOrg/gravity-cli/assets/57003432/3458f35c-aa26-4479-8683-71b465d58a5b)
2. Create data product and ruleset with schema
![image](https://github.com/BrobridgeOrg/gravity-cli/assets/57003432/924a3f7b-065e-48f1-95c1-53b691f92b55)
![image](https://github.com/BrobridgeOrg/gravity-cli/assets/57003432/e6e9d7f3-3911-489e-bcc1-03e0676e7ba4)
3. Publish an event with pk in payload
4. Publish an event without pk in payload, but in schema.
5. Publish an event with pk in payload.
(Step 3 to Step 5 need operate faster)
![image](https://github.com/BrobridgeOrg/gravity-cli/assets/57003432/d5072c5f-e121-4495-a55a-d0eaeca712fc)
6. Using subscribe command we can see payload's information had been combined.
![image](https://github.com/BrobridgeOrg/gravity-cli/assets/57003432/e8893921-d5f1-4b38-bdae-110047ca7fd7)

## Full video
https://github.com/BrobridgeOrg/gravity-cli/assets/57003432/255ea668-daa2-4384-9d38-0d89e21968e2

**Comment by william-wyliang** [comment]
This is an issue that needs to be fixed.

**Comment by cfsghost** [comment]
the bug has been addressed in the [gravity-dispatcher](https://github.com/BrobridgeOrg/gravity-dispatcher).

it has been fixed, you can test the latest release from gravity-dispatcher repository with the tag version v0.0.3+.

https://github.com/BrobridgeOrg/gravity-dispatcher/releases/tag/v0.0.3

**Comment by william-wyliang** [comment]
@TaroBill Please arrange to verify this version.

**Comment by TaroBill** [comment]
After testing the latest version, the bug has been confirmed as fixed. Thank you.
