### ISSUE TITLE
Issues with command help messages

### ISSUE THREAD

**Issue by Eeec7777** [BrobridgeOrg/gravity-cli#11]
Version: [[47ca8b6](https://github.com/BrobridgeOrg/gravity-cli/commit/47ca8b652eb4b3032934fb348d07b0f7c889d687)]

## Issue 1: Duplicate (default true) in Command Usage for `token create` and `token update`
In the command usage for `token create` and `token update`, the `--enabled` flag description includes two (default true).
This occurs because both the manual description and Cobra automatically append (default true).

### Reproduce:
1. Run `token create -h` or `token update -h`.
2. The usage for the `--enabled` flag contains two (default true).
![image](https://github.com/BrobridgeOrg/gravity-cli/assets/125728481/722db5f9-ffdb-496f-b879-b9ab2c6f0de1)

### Suggested Solution:
Remove the manually added (default true) from the flag description for both commands.

## Issue 2: Incomplete description for `--enabled` in `product update`
The description for the `--enabled` flag in the `product update` command is missing a character and default prompt.

### Reproduce:
1. Run `product update -h`.
2. The usage for the `--enabled` flag reads "Enable produc".
![image](https://github.com/BrobridgeOrg/gravity-cli/assets/125728481/4ae7147b-87e1-4bcb-a345-c00eec512b7b)

### Suggested Solution:
Correct the description to "Enable product (default false)".

## Issue 3: Duplicate default prompt and missing usage information for `product sub `
The description for the `--partitions` flag in the `product sub` command includes two default value prompt. Additionally, the usage information should include a prompt that multiple values can be specified, separated by commas.

### Reproduce:
1. Run `product sub -h`.
2. The usage for the `--partitions` flag contains duplicate default prompts and lacks information on specifying multiple values.
![image](https://github.com/BrobridgeOrg/gravity-cli/assets/125728481/05e38d55-82cf-44a9-9626-036a4e49276c)

**Comment by william-wyliang** [comment]
These issues should be easily fixed. Please consider contributing by sending your PRs.
